apiVersion: v1
kind: Secret
metadata:
  name: betzone-secrets
  namespace: betzone
  labels:
    app.kubernetes.io/name: betzone
type: Opaque
stringData:
  # TODO: replace with sealed-secrets or external secret manager in production
  JWT_SECRET: super_secret_jwt_key_change_in_production
  INTERNAL_API_KEY: internal_service_key_change_me
  AUTH_DB_USER: betzone
  AUTH_DB_PASS: betzone_secret
  WALLET_DB_USER: betzone
  WALLET_DB_PASS: betzone_secret
  BETTING_DB_USER: betzone
  BETTING_DB_PASS: betzone_secret
  CASINO_DB_USER: betzone
  CASINO_DB_PASS: betzone_secret
  CHAT_DB_USER: betzone
  CHAT_DB_PASS: betzone_secret
  POSTGRES_USER: betzone
  POSTGRES_PASSWORD: betzone_secret
  RABBITMQ_DEFAULT_USER: betzone
  RABBITMQ_DEFAULT_PASS: betzone_secret
  SMTP_USER: ""
  SMTP_PASS: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GRAFANA_ADMIN_PASSWORD: admin
